export type Lang = 'kz' | 'ru'

export const t = {
  kz: {
    appName: 'Дүкен кассасы',
    login: 'Кіру',
    register: 'Тіркелу',
    email: 'Email',
    password: 'Құпия сөз',
    loginBtn: 'Кіру',
    registerBtn: 'Тіркелу',
    noAccount: 'Аккаунт жоқ па?',
    hasAccount: 'Аккаунт бар ма?',
    storeName: 'Дүкен атауы',
    createStore: 'Дүкен жасау',
    createStoreTitle: 'Дүкеніңізді жасаңыз',
    home: 'Басты',
    sale: 'Сату',
    stock: 'Склад',
    report: 'Отчет',
    todayRevenue: 'Бүгінгі түсім',
    transactions: 'Транзакция',
    cash: 'Наличный',
    kaspi: 'Kaspi',
    recentSales: 'Соңғы сатылымдар',
    noSales: 'Сатылым жоқ',
    lowStock: 'Аз қалған товарлар',
    newSale: 'Жаңа сату',
    selectProduct: 'Товар таңдаңыз',
    quantity: 'Саны',
    paymentType: 'Төлем түрі',
    total: 'Жалпы',
    sell: 'Сату жасау',
    addProduct: 'Товар қосу',
    productName: 'Товар аты',
    price: 'Баға (₸)',
    qty: 'Саны',
    add: 'Қосу',
    products: 'Товарлар тізімі',
    noProducts: 'Товар жоқ',
    dailyReport: 'Күнделікті есеп',
    totalRevenue: 'Жалпы түсім',
    txCount: 'Транзакция саны',
    topSales: 'Көп сатылған',
    noData: 'Мәлімет жоқ',
    logout: 'Шығу',
    notEnoughStock: 'Жеткілікті товар жоқ!',
    fillAll: 'Барлық өрісті толтырыңыз',
    pieces: 'дана',
    loading: 'Жүктелуде...',
  },
  ru: {
    appName: 'Касса магазина',
    login: 'Вход',
    register: 'Регистрация',
    email: 'Email',
    password: 'Пароль',
    loginBtn: 'Войти',
    registerBtn: 'Зарегистрироваться',
    noAccount: 'Нет аккаунта?',
    hasAccount: 'Уже есть аккаунт?',
    storeName: 'Название магазина',
    createStore: 'Создать магазин',
    createStoreTitle: 'Создайте ваш магазин',
    home: 'Главная',
    sale: 'Продажа',
    stock: 'Склад',
    report: 'Отчёт',
    todayRevenue: 'Выручка сегодня',
    transactions: 'Транзакций',
    cash: 'Наличные',
    kaspi: 'Kaspi',
    recentSales: 'Последние продажи',
    noSales: 'Нет продаж',
    lowStock: 'Мало товара',
    newSale: 'Новая продажа',
    selectProduct: 'Выберите товар',
    quantity: 'Количество',
    paymentType: 'Тип оплаты',
    total: 'Итого',
    sell: 'Продать',
    addProduct: 'Добавить товар',
    productName: 'Название товара',
    price: 'Цена (₸)',
    qty: 'Количество',
    add: 'Добавить',
    products: 'Список товаров',
    noProducts: 'Нет товаров',
    dailyReport: 'Дневной отчёт',
    totalRevenue: 'Общая выручка',
    txCount: 'Кол-во транзакций',
    topSales: 'Топ продаж',
    noData: 'Нет данных',
    logout: 'Выйти',
    notEnoughStock: 'Недостаточно товара!',
    fillAll: 'Заполните все поля',
    pieces: 'шт',
    loading: 'Загрузка...',
  }
}
